path:
  css: css
  out: H:/Code/Steam/md-steam/src/main/resources/out
match-mode:
  domain: domain
  url: url
  url-prefix: url-prefix
  regexp: regexp
configs:
  - note: md颜色
    file-name: mdColor.css
    matches:
      - mode: domain
        params:
          - keylol.com
  - note: 变量配置
#    file-name: var.css
    file-name: optional.txt
    matches:
      - mode: domain
        params:
          - keylol.com
  - note: 导航栏
    file-name: nav.css
    matches:
      - mode: domain
        params:
          - keylol.com
  - note: 首页
    file-name: home.css
    matches:
      - mode: regexp
        params:
          - https?://keylol.com(/forum.php)?
  - note: 帖子内容
    file-name: post.css
    matches:
      - mode: url-prefix
        params:
          - https://keylol.com/t
          - https://keylol.com/forum.php?mod=viewthread&t
  - note: 板块（帖子列表）
    file-name: postList.css
    matches:
      - mode: regexp
        params:
          - ".+keylol.com/f[0-9]{3}.+"
          - ".+keylol.com.+forumdisplay.+fid=[0-9]+.+"
  - note: 导读
    file-name: guide.css
    matches:
      - mode: url-prefix
        params:
          - http://keylol.com/forum.php?mod=guide
          - https://keylol.com/forum.php?mod=guide
  - note: 导读的“最新热门”、“最新回复”、“最新发表”、“我的帖子”
    file-name: guide-new-hot-my.css
    matches:
      - mode: url-prefix
        params:
          - http://keylol.com/forum.php?mod=guide
          - https://keylol.com/forum.php?mod=guide
  - note: 导读的“最新精华”、“抢沙发”
    file-name: guide-digest-sofa.css
    matches:
      - mode: regexp
        params:
          - ".+keylol.com.+mod=guide&view=(digest|sofa)"
  - note: 导读的“我的帖子”
    file-name: guide-my.css
    matches:
      - mode: regexp
        params:
          - ".+keylol.com.+mod=guide&view=my"